// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtZ4v8_pncyA-hR_lomLtkSoNpdbALZQU',
    appId: '1:1023705724730:web:e3fef021b155934f248203',
    messagingSenderId: '1023705724730',
    projectId: 'visionguard-c6bab',
    authDomain: 'visionguard-c6bab.firebaseapp.com',
    storageBucket: 'visionguard-c6bab.appspot.com',
    measurementId: 'G-5GF0XWT7E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnpnDnpzjtP-R9JqN-JVP-Rd3qaqlbmvw',
    appId: '1:1023705724730:android:78415e68fda3af0b248203',
    messagingSenderId: '1023705724730',
    projectId: 'visionguard-c6bab',
    storageBucket: 'visionguard-c6bab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCSxMVJFBYHesylummCrUqHqGIAAkIatw',
    appId: '1:1023705724730:ios:83d862954bb1b47d248203',
    messagingSenderId: '1023705724730',
    projectId: 'visionguard-c6bab',
    storageBucket: 'visionguard-c6bab.appspot.com',
    iosBundleId: 'com.example.visionguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCSxMVJFBYHesylummCrUqHqGIAAkIatw',
    appId: '1:1023705724730:ios:a0c2ade46a5fb018248203',
    messagingSenderId: '1023705724730',
    projectId: 'visionguard-c6bab',
    storageBucket: 'visionguard-c6bab.appspot.com',
    iosBundleId: 'com.example.visionguard.RunnerTests',
  );
}
